INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Some project name", "Environmental", 50000, "2018-06-25", "2018-07-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Some project name2", "Food", 800, "2018-06-25", "2018-07-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Some project name3", "Environmental", 25000, "2018-06-25", "2018-07-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Some project name4", "Music", 5000, "2018-06-25", "2018-07-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Some project name5", "Food", 1200, "2018-06-25", "2018-07-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Some project name6", "Music", 6000, "2018-06-25", "2018-07-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Some project name7", "Environmental", 34000, "2018-06-25", "2018-07-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Some project name8", "Computer Hardware", 50000, "2018-06-25", "2018-07-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Some project name9", "Food", 400, "2018-06-25", "2018-07-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Some project name10", "Art", 1300, "2018-06-25", "2018-07-31");

INSERT INTO users (name, age) VALUES ("Anthony", 11);
INSERT INTO users (name, age) VALUES ("Andre", 22);
INSERT INTO users (name, age) VALUES ("Marlon", 33);
INSERT INTO users (name, age) VALUES ("Steven", 44);
INSERT INTO users (name, age) VALUES ("Toni", 55);
INSERT INTO users (name, age) VALUES ("Peter", 66);
INSERT INTO users (name, age) VALUES ("Alex", 77);
INSERT INTO users (name, age) VALUES ("Daniel", 88);
INSERT INTO users (name, age) VALUES ("Anthony", 12);
INSERT INTO users (name, age) VALUES ("Andre", 23);
INSERT INTO users (name, age) VALUES ("Marlon", 34);
INSERT INTO users (name, age) VALUES ("Steven", 45);
INSERT INTO users (name, age) VALUES ("Toni", 56);
INSERT INTO users (name, age) VALUES ("Peter", 67);
INSERT INTO users (name, age) VALUES ("Alex", 78);
INSERT INTO users (name, age) VALUES ("Daniel", 89);
INSERT INTO users (name, age) VALUES ("Anthony", 13);
INSERT INTO users (name, age) VALUES ("Andre", 24);
INSERT INTO users (name, age) VALUES ("Marlon", 35);
INSERT INTO users (name, age) VALUES ("Steven", 46);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 6, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (120, 11, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 19, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 2, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (220, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 20, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 4, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 3, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (175, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (105, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 13, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (130, 14, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (140, 19, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 17, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 14, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (120, 12, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 20, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 2, 10);
