insert into users (name, age) values (	'A',	1	);
insert into users (name, age) values (	'B',	2	);
insert into users (name, age) values (	'C',	3	);
insert into users (name, age) values (	'D',	4	);
insert into users (name, age) values (	'E',	5	);
insert into users (name, age) values (	'F',	6	);
insert into users (name, age) values (	'G',	7	);
insert into users (name, age) values (	'H',	8	);
insert into users (name, age) values (	'I',	9	);
insert into users (name, age) values (	'J',	10	);
insert into users (name, age) values (	'K',	11	);
insert into users (name, age) values (	'L',	12	);
insert into users (name, age) values (	'M',	13	);
insert into users (name, age) values (	'N',	14	);
insert into users (name, age) values (	'O',	15	);
insert into users (name, age) values (	'P',	16	);
insert into users (name, age) values (	'Q',	17	);
insert into users (name, age) values (	'R',	18	);
insert into users (name, age) values (	'S',	19	);
insert into users (name, age) values (	'T',	20	);

insert into projects (title, category, funding_goal, start_date, end_date) values ('Pro1',	'Music',	30000,	'2018-07-02',	'2018-07-03'	);
insert into projects (title, category, funding_goal, start_date, end_date) values ('Pro2',	'Cat1',	30000,	'2018-07-03',	'2018-07-04'	);
insert into projects (title, category, funding_goal, start_date, end_date) values ('Pro3',	'Cat1',	30000,	'2018-07-04',	'2018-07-05'	);
insert into projects (title, category, funding_goal, start_date, end_date) values ('Pro4',	'Cat1',	30000,	'2018-07-05',	'2018-07-06'	);
insert into projects (title, category, funding_goal, start_date, end_date) values ('Pro5',	'Cat1',	30000,	'2018-07-06',	'2018-07-07'	);
insert into projects (title, category, funding_goal, start_date, end_date) values ('Pro6',	'Cat1',	30000,	'2018-07-07',	'2018-07-08'	);
insert into projects (title, category, funding_goal, start_date, end_date) values ('Pro7',	'Cat1',	30000,	'2018-07-08',	'2018-07-09'	);
insert into projects (title, category, funding_goal, start_date, end_date) values ('Pro8',	'Cat1',	30000,	'2018-07-09',	'2018-07-10'	);
insert into projects (title, category, funding_goal, start_date, end_date) values ('Pro9',	'Cat1',	30000,	'2018-07-10',	'2018-07-11'	);
insert into projects (title, category, funding_goal, start_date, end_date) values ('Pro10',	'Cat1',	30000,	'2018-07-11',	'2018-07-12'	);


insert into pledges (amount, user_id, project_id) values (	31	,	1	,	1	);
insert into pledges (amount, user_id, project_id) values (	1	,	2	,	2	);
insert into pledges (amount, user_id, project_id) values (	2	,	3	,	3	);
insert into pledges (amount, user_id, project_id) values (	2000	,	4	,	4	);
insert into pledges (amount, user_id, project_id) values (	123	,	5	,	5	);
insert into pledges (amount, user_id, project_id) values (	43214	,	6	,	6	);
insert into pledges (amount, user_id, project_id) values (	43241	,	7	,	7	);
insert into pledges (amount, user_id, project_id) values (	1261	,	8	,	8	);
insert into pledges (amount, user_id, project_id) values (	4321	,	9	,	9	);
insert into pledges (amount, user_id, project_id) values (	989	,	10	,	10	);
insert into pledges (amount, user_id, project_id) values (	24342	,	1	,	1	);
insert into pledges (amount, user_id, project_id) values (	112372	,	2	,	2	);
insert into pledges (amount, user_id, project_id) values (	342	,	3	,	3	);
insert into pledges (amount, user_id, project_id) values (	546	,	4	,	4	);
insert into pledges (amount, user_id, project_id) values (	63264	,	5	,	5	);
insert into pledges (amount, user_id, project_id) values (	534253	,	6	,	6	);
insert into pledges (amount, user_id, project_id) values (	64326	,	7	,	7	);
insert into pledges (amount, user_id, project_id) values (	643	,	8	,	8	);
insert into pledges (amount, user_id, project_id) values (	6346	,	9	,	9	);
insert into pledges (amount, user_id, project_id) values (	6432234	,	10	,	10	);
insert into pledges (amount, user_id, project_id) values (	14312	,	11	,	1	);
insert into pledges (amount, user_id, project_id) values (	14124	,	12	,	2	);
insert into pledges (amount, user_id, project_id) values (	3415	,	13	,	3	);
insert into pledges (amount, user_id, project_id) values (	657	,	14	,	4	);
insert into pledges (amount, user_id, project_id) values (	867	,	15	,	5	);
insert into pledges (amount, user_id, project_id) values (	99	,	16	,	6	);
insert into pledges (amount, user_id, project_id) values (	56	,	17	,	7	);
insert into pledges (amount, user_id, project_id) values (	64	,	18	,	8	);
insert into pledges (amount, user_id, project_id) values (	345	,	19	,	9	);
insert into pledges (amount, user_id, project_id) values (	543	,	20	,	10	);
